In [1]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [3]:
np.random.shuffle(arr)

In [4]:
arr

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

In [5]:
import numpy as np
arr=np.array([10,20,30,40,50])
np.unique(arr).size


5

In [6]:
arr=np.array([10,20,30,40,10,20,30])
np.unique(arr,return_index=True,return_counts=True)

(array([10, 20, 30, 40]),
 array([0, 1, 2, 3], dtype=int64),
 array([2, 2, 2, 1], dtype=int64))

## numpy stacking

there are two types vertical and horizonata stacking

In [7]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(50,71,9).reshape(3,3)
np.hstack((arr1,arr2))

array([[16, 11, 13, 59, 56, 64],
       [17, 13, 16, 53, 54, 69],
       [ 3, 16, 11, 69, 63, 50]])

In [10]:
arr1

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [11]:
arr2

array([[59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])