In [1]:
# numpy array funtion
import numpy as np
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [2]:
np.min(arr)

10

In [3]:
np.max(arr)

50

In [4]:
np.argmin(arr)

0

In [5]:
np.argmax(arr)

4

In [7]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [8]:
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [9]:
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [10]:
#linspace
np.linspace(1,2,5)# it give number between 1 to 2 which give 5 element and the difference between them is same


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
# for 2D array
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)

In [12]:
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [13]:
np.sum(matrix)

116

In [14]:
matrix.sum()

116

In [15]:
np.min(matrix)

3

In [16]:
np.max(matrix)

17

In [17]:
np.min(matrix,axis=0)

array([ 3, 11, 11])

In [18]:
np.min(matrix,axis=1)

array([11, 13,  3])

In [19]:
np.max(matrix,axis=1)

array([16, 17, 16])

In [20]:
np.cumsum(matrix)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])