In [3]:
#1. Write a Python program to find the maximum and minimum value of a given flattened array.

array1=[2,3,4,86,38,40,4]
array2=[5,74,643,89,42,7]
print(max(array1))
print(min(array1))

print(max(array2))
print(min(array2))

86
2
643
5


In [18]:
#2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis. 
import numpy as np
x=np.arange(9).reshape((3,3))
print(x)

print("max value in x is:",np.amax(x))
print("min value in x is:",np.amin(x))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
max value in x is: 8
min value in x is: 0


In [36]:
#3 MEAN
data=[23,46,364,86,44,76,8,896,4,2,4,4,4,4,4,4,56,800,6,5,80,5,3,6,841,35,8995,3,60]

mean=sum(data)/len(data)
print("mean of the data is:",mean)

mean of the data is: 429.9310344827586


In [47]:
#4 MEDIAN
sorted_data=sorted(data)
print(sorted_data)
median=(len(sorted_data)+1)/2
print('median of the data is:',median)



[2, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6, 8, 23, 35, 44, 46, 56, 60, 76, 80, 86, 364, 800, 841, 896, 8995]
median of the data is: 15.0


In [42]:
#5MODE
def find_mode(_sorted_data):
    data_counts = {}# Create a dictionary to store the frequency of each data point.
    for item in sorted_data:
        
        if item in data_counts:
            data_counts[item] += 1
        else:
            data_counts[item] = 1
    max_count = max(data_counts.values())# Find the data point(s) with the highest frequency.
    modes = [item for item, count in data_counts.items() if count == max_count]

  # Return the mode(s) only if there's a unique most frequent value(s).
    return modes if max_count > 1 else None

# Example usage
modes = find_mode(sorted_data)
print(f"The mode(s) of the data is/are: {modes}")

The mode(s) of the data is/are: [4]


In [43]:
#6
import statistics

In [46]:
print("mean of the data is:",statistics.mean(sorted_data))
print("mode of the data is:",statistics.mode(sorted_data))
print("median of the data is:",statistics.median(sorted_data))
print("standard deviation of the data is:",statistics.stdev(sorted_data))
print("variance of the data is:",statistics.variance(sorted_data))


mean of the data is: 429.9310344827586
mode of the data is: 4
median of the data is: 8
standard deviation of the data is: 1667.5974148250034
variance of the data is: 2780881.1379310344


In [48]:
#7
q1=len(sorted_data)*25/100
q1


7.25

In [51]:
#8
q1=sorted_data[7]+0.25*(sorted_data[8]-sorted_data[7])
q1

4.0

In [54]:
#9
q3=len(sorted_data)*75/100
q3

21.75

In [55]:
#10
q3=sorted_data[21]+0.75*(sorted_data[22]-sorted_data[21])
q3

79.0

In [56]:
IQR= q3-q1
IQR

75.0

In [58]:
#11
lower_bound=q1-1.5*(IQR)
print("lower bound of the data is:",lower_bound)

upper_bound=q3+1.5*(IQR)
print("upper bound of the data is:",upper_bound)


lower bound of the data is: -108.5
upper bound of the data is: 191.5
