In [2]:
#1 
import numpy as np
a=[1,2,3]
a

[1, 2, 3]

In [4]:
#2 1D array
import numpy as np
a=[1,2,3,4]
arr1=np.array(a)
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
myarr=np.array([1,2,3,4,5])
myarr

array([1, 2, 3, 4, 5])

In [8]:
#3
a=[]
n=int(input('enter the size:'))

for i in range(n):
    val=int(input('enter the value:'))
    a.append(val)
    arr=np.array(a)
print(arr)

enter the size:5
enter the value:1
enter the value:2
enter the value:3
enter the value:4
enter the value:5
[1 2 3 4 5]


In [9]:
#4 
arr.sort()

In [15]:
arr 

array([1, 2, 3, 4, 5])

In [ ]:
#5  2D array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

In [18]:
type(arr2)

numpy.ndarray

## function zero

In [22]:
a=np.zeros(4)

In [23]:
a

array([0., 0., 0., 0.])

In [33]:
a=np.zeros([5,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## function ones

In [31]:
a=np.ones(5)

In [32]:
a

array([1., 1., 1., 1., 1.])

In [34]:
a=np.ones([4,3])

In [35]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## function eye

In [36]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## function diag

In [37]:
arr=np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [39]:
np.diag(arr)

array([1, 2, 3, 4])

## function rand

In [41]:
a=np.random.rand(5)
a

array([0.62515655, 0.70278747, 0.42723547, 0.04542148, 0.07614512])

In [42]:
arr1=np.random.rand(2,3)
arr1

array([[0.60336657, 0.59652606, 0.54393194],
       [0.69150843, 0.66735777, 0.17633668]])

## function randn

In [43]:
a=np.random.randn(3)
a

array([0.76967783, 1.05015415, 0.11527589])

## function randint

In [44]:
a=np.random.randint(1,6)
a

5