In [1]:
#1. Check Anagram:
def is_anagram(s1,s2):
    return sorted(s1)==sorted(s2)

string1=input('enter string1:')
string2=input('enter string2:')

if is_anagram(string1,string2):
    print('anagram')
else:
    print('not anagram')

enter string1:abhinav
enter string2:srujan
not anagram


In [8]:
#2. Generate a Random Number:
import random

print('random number',random.randint(1,50))

random number 29


In [15]:
#3. Binary Search Algorithm:
def binary_search(arr,x):
    low=0
    high=len(arr)-1
    while low>=high:
        mid=(low+high)//2
        if arr[mid]<x:
            low=mid+1
        elif arr[mid]>x:
            high=mid-1
        else:
            return mid
        return -1
arr=[2,3,4,10,40]
x=10
result= binary_search(arr,x)

if result !=-1:
    print(f"Element found at index {result}")
else:
    print('element not found')

Element found at index None


In [1]:
#4. sclicing
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
a


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
a[:2,1:3]

array([[20, 30],
       [50, 60]])

In [5]:
import numpy as np
np.random.seed(111)
a=np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [6]:
a[2:,2:]

array([[442,   8, 269],
       [369, 217, 285],
       [ 22,  55, 201],
       [231, 187, 269]])

In [7]:
a[3:5,2:]

array([[369, 217, 285],
       [ 22,  55, 201]])

In [8]:
# view vs copy
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6]
slicing[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [9]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6].copy()
slicing[:]=0
a


array([10, 20, 30, 40, 50, 60, 70, 80])

In [10]:
slicing

array([0, 0, 0])

In [11]:
#conditional selectional
import numpy as np
arr=np.arange(1,16)
b=arr>10
arr[b]

array([11, 12, 13, 14, 15])

In [12]:
arr[arr<5]


array([1, 2, 3, 4])

In [13]:
arr[arr%2==0]=0

In [14]:
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [15]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [16]:
# various opereation on numpy array
import numpy as np
a=np.arange(1,6)
b=np.arange(6,11)
print(a)
print(b)


[1 2 3 4 5]
[ 6  7  8  9 10]


In [17]:
a*2

array([ 2,  4,  6,  8, 10])

In [18]:
a+2

array([3, 4, 5, 6, 7])

In [19]:
a**a

array([   1,    4,   27,  256, 3125])

In [20]:
a+b

array([ 7,  9, 11, 13, 15])

In [21]:
a-b

array([-5, -5, -5, -5, -5])

In [22]:
b-a

array([5, 5, 5, 5, 5])

In [23]:
# for 2D
c=np.array([1,2,3,4]).reshape(2,2)
d=np.array([5,6,7,8]).reshape(2,2)

In [24]:
c

array([[1, 2],
       [3, 4]])

In [25]:
d

array([[5, 6],
       [7, 8]])

In [26]:
c.dot(d)

array([[19, 22],
       [43, 50]])

In [27]:
c+d

array([[ 6,  8],
       [10, 12]])

In [28]:
c**d

array([[    1,    64],
       [ 2187, 65536]])

In [29]:
d-c

array([[4, 4],
       [4, 4]])